---
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/c18t/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: yamllint
      - id: hadolint
