version: '3'

services:

  gatsby:
    build:
      context: .
    container_name: gatsby
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - './article:/var/opt/app/article'
      - './src:/var/opt/app/src'
      - './gatsby-config.ts:/var/opt/app/gatsby-config.ts'
      - './gatsby-node.ts:/var/opt/app/gatsby-node.ts'
      - './package.json:/var/opt/app/package.json'
      - './pnpm-lock.yaml:/var/opt/app/pnpm-lock.yaml'
      - './tsconfig.json:/var/opt/app/tsconfig.json'
